version: '3'
services:
  cass:
    image: cassandra:latest
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7199:7199"
    deploy:
      placement:
        constraints:
          #- node.hostname == iot-vm3
          - node.Hostname == CORE_DB_HOSTNAME
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        window: 120s
      placement:
        constraints:
          - node.hostname == SWARM_AGG_HOSTNAME
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
      restart_policy:
        condition: on-failure
        window: 120s
      placement:
        constraints:
          - node.hostname == SWARM_AGG_HOSTNAME
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: SWARM_AGG
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "stats:1:1"
      KAFKA_ZOOKEEPER_CONNECT: SWARM_AGG:2181
