version: "3"
services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:5.4.1
    hostname: "IoT-app-controller"
    deploy:
      mode: global
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /home/ubuntu/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    networks:
      - host
    environment:
      - system.hostfs=/hostfs
networks:
  host:
